# Note: This is a template. Use sealed-secrets or external-secrets in production!
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: ux-flow-engine
type: Opaque
stringData:
  uri: "mongodb://admin:changeme@mongodb:27017/ux-flow-engine?authSource=admin&replicaSet=rs0"
  root-username: "admin"
  root-password: "changeme"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: ux-flow-engine
type: Opaque
stringData:
  url: "redis://:changeme@redis:6379"
  password: "changeme"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: ux-flow-engine
type: Opaque
stringData:
  secret: "your-very-secure-jwt-secret-minimum-32-characters"
  refresh-secret: "your-very-secure-refresh-secret-minimum-32-characters"
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
  namespace: ux-flow-engine
type: Opaque
stringData:
  secret-key: "sk_live_xxx"
  webhook-secret: "whsec_xxx"
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth-secret
  namespace: ux-flow-engine
type: Opaque
stringData:
  google-client-id: "xxx.apps.googleusercontent.com"
  google-client-secret: "xxx"
  github-client-id: "xxx"
  github-client-secret: "xxx"
---
apiVersion: v1
kind: Secret
metadata:
  name: encryption-secret
  namespace: ux-flow-engine
type: Opaque
stringData:
  key: "your-32-character-encryption-key"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-key
  namespace: ux-flow-engine
type: Opaque
stringData:
  replica.key: |
    your-mongodb-replica-set-key-here