apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
  labels:
    app: user-management
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
        version: v1
    spec:
      containers:
      - name: user-management
        image: ux-flow-engine/user-management:latest
        ports:
        - containerPort: 3004
        env:
        - name: NODE_ENV
          value: "production"
        - name: USER_MANAGEMENT_PORT
          value: "3004"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: user-management-secrets
              key: mongodb-uri
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: user-management-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: user-management-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 3004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3004
          initialDelaySeconds: 10
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30

---
apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  labels:
    app: user-management
spec:
  selector:
    app: user-management
  ports:
  - port: 3004
    targetPort: 3004
    protocol: TCP
    name: http
  type: ClusterIP

---
apiVersion: v1
kind: Secret
metadata:
  name: user-management-secrets
type: Opaque
stringData:
  mongodb-uri: "mongodb://mongo-service:27017/ux-flow-engine"
  redis-url: "redis://redis-service:6379"
  jwt-secret: "your-production-jwt-secret-here"